### ISSUE TITLE
MonthCalendar在xml中的visibility 为gone,首次加载必然崩溃.

### ISSUE THREAD

**Issue by 2ndtonone** [yannecer/NCalendar#34]
`java.lang.NullPointerException: Attempt to invoke virtual method 'org.joda.time.LocalDate com.necer.view.BaseCalendarView.getInitialDate()' on a null object reference
        at com.necer.calendar.BaseCalendar.drawView(BaseCalendar.java:153)
        at com.necer.calendar.BaseCalendar.access$000(BaseCalendar.java:30)
        at com.necer.calendar.BaseCalendar$1$1.run(BaseCalendar.java:80)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by yannecer** [comment]
@2ndtonone 刚已经解决了，提交代码了
