### ISSUE TITLE
com.necer.utils.ViewUtil$ViewException

### ISSUE THREAD

**Issue by PiPiCaptain** [yannecer/NCalendar#46]
2019-08-17 15:12:42.890 23931-23931/com.guokai.mobile W/System.err: com.necer.utils.ViewUtil$ViewException
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at com.necer.utils.ViewUtil.traverseView(ViewUtil.java:39)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at com.necer.utils.ViewUtil.traverseView(ViewUtil.java:41)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at com.necer.utils.ViewUtil.getTargetView(ViewUtil.java:21)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at com.necer.calendar.NCalendar.onInterceptTouchEvent(NCalendar.java:431)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2524)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.891 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.892 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2988)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2613)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:530)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3503)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:480)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.View.dispatchPointerEvent(View.java:12155)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5366)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5118)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4767)
2019-08-17 15:12:42.893 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4824)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7294)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7268)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7229)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7397)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.os.Looper.loop(Looper.java:170)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7055)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
2019-08-17 15:12:42.894 23931-23931/com.guokai.mobile W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

**Comment by PiPiCaptain** [comment]
@yannecer 解决了？请问什么时候会更新？

**Comment by yannecer** [comment]
@PiPiCaptain 我没有发现是什么问题，你说下怎么复现，我模拟器、真机都没有出现这个问题

**Comment by yannecer** [comment]
@PiPiCaptain 能说下复现流程吗？

**Comment by yannecer** [comment]
手机型号，系统版本，复现流程等 @1405553774

**Comment by 1405553774** [comment]
荣耀青春版本   android 8 ,  点击 选择某天的日期就会报 ：

2021-09-17 17:21:40.002 31884-31884/com.shuge.smallcoup W/System.err: com.necer.utils.ViewUtil$ViewException
2021-09-17 17:21:40.003 31884-31884/com.shuge.smallcoup W/System.err:     at com.necer.utils.ViewUtil.traverseView(ViewUtil.java:39)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at com.necer.utils.ViewUtil.traverseView(ViewUtil.java:41)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at com.necer.utils.ViewUtil.getTargetView(ViewUtil.java:21)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at com.necer.calendar.NCalendar.onInterceptTouchEvent(NCalendar.java:486)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2515)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.004 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
2021-09-17 17:21:40.005 31884-31884/com.shuge.smallcoup W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
2021-09-17 17:21:40.006 31884-31884/com.shuge.smallcoup W/System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
2021-09-17 17:21:40.006 31884-31884/com.shuge.smallcoup W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
2021-09-17 17:21:40.006 31884-31884/com.shuge.smallcoup W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3559)

**Comment by 1405553774** [comment]
我们出现这个问他目前使用的场景是这样：Miui10Calendar 下面嵌套了  ViewPager  ，ViewPager里面有两个 fragment ,  两个fragment 中有 上拉更新下拉刷新的控件 （  SmartRefreshLayout  嵌套RecyclerView）

**Comment by yannecer** [comment]
@1405553774 我身边没有荣耀青春版本 android 8的手机，我用安卓8模拟器试了下，没有发现问题，从日志上看，好像是 我用的一个异常出现了问题，这个异常是为了及时中断循环，目的是为了找到xml布局中的实现了 NestscrollChild的 view，你可以在这个view上加上tag，R.string.N_factual_scroll_view  这样就不会走这个异常了，应该就不会报这个错误了，具体可以参考 activity_miui9.xml文件的第105行，给RecyclerView设置一个tag，android:tag="@string/N_factual_scroll_view" 你试下

**Comment by yannecer** [comment]
@1405553774 你可以试是在 SmartRefreshLayout 上加上tag，试下
