### ISSUE TITLE
日历崩溃：KotlinNullPointerException

### ISSUE THREAD

**Issue by victorfan336** [yannecer/NCalendar#97]
复现步骤：从其他页面切换到日历页后就崩溃了，偶先，容易在第一次安装使用的时候出现，后面极难出现。
android 系统： android 14
android 机型： 红米K60，其他设备如华为也都出现过。
CPU架构：arm64-v8a

崩溃日志：

com.necer.calendar.NViewPager$a$a.run(Unknown Source:191)
2
android.os.Handler.handleCallback(Handler.java:958)
3
android.os.Handler.dispatchMessage(Handler.java:99)
4
android.os.Looper.loopOnce(Looper.java:205)
5
android.os.Looper.loop(Looper.java:294)
6
android.app.ActivityThread.main(ActivityThread.java:8376)
7
java.lang.reflect.Method.invoke(Native Method)
8
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
9
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)

@yannecer 麻烦看看，谢谢

**Comment by victorfan336** [comment]
bugly上的崩溃日志：
<html>
<body>

12-19 15:11:56.065 4707 4707 E CrashReport: stack frame :9, has cause false
--
8412-19 15:11:56.066 4707 4707 E CrashReport: #++++++++++Record By Bugly++++++++++#
8512-19 15:11:56.066 4707 4707 E CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
8612-19 15:11:56.066 4707 4707 E CrashReport: # PKG NAME: com.xx.xxx
8712-19 15:11:56.066 4707 4707 E CrashReport: # APP VER: 1.0.0
8812-19 15:11:56.066 4707 4707 E CrashReport: # SDK VER: 4.1.9.2-4.1.9.2
8912-19 15:11:56.066 4707 4707 E CrashReport: # LAUNCH TIME: 2024-12-19 15:09:37
9012-19 15:11:56.066 4707 4707 E CrashReport: # CRASH TYPE: JAVA_CRASH
9112-19 15:11:56.066 4707 4707 E CrashReport: # CRASH TIME: 2024-12-19 15:11:56
9212-19 15:11:56.066 4707 4707 E CrashReport: # CRASH PROCESS: com.xx.xxx
9312-19 15:11:56.066 4707 4707 D CrashReport: isAppForeground:true
9412-19 15:11:56.066 4707 4707 E CrashReport: # CRASH FOREGROUND: true
9512-19 15:11:56.066 4707 4707 E CrashReport: # CRASH THREAD: main
9612-19 15:11:56.066 4707 4707 E CrashReport: # REPORT ID: 2ab4b69c-14a4-4596-8328-3125ca4f1881
9712-19 15:11:56.066 4707 4707 E CrashReport: # CRASH DEVICE: ums9621_1h10_native UNROOT
9812-19 15:11:56.066 4707 4707 E CrashReport: # RUNTIME AVAIL RAM:3590967296 ROM:118169440256 SD:118169440256
9912-19 15:11:56.066 4707 4707 E CrashReport: # RUNTIME TOTAL RAM:5709889536 ROM:120176246784 SD:120176246784
10012-19 15:11:56.066 4707 4707 E CrashReport: # CRASH STACK:
10112-19 15:11:56.066 4707 4707 E CrashReport: Y3.h
10212-19 15:11:56.066 4707 4707 E CrashReport: at com.necer.calendar.NViewPager$a$a.run(Unknown Source:191)
10312-19 15:11:56.066 4707 4707 E CrashReport: at android.os.Handler.handleCallback(Handler.java:958)
10412-19 15:11:56.066 4707 4707 E CrashReport: at android.os.Handler.dispatchMessage(Handler.java:99)
10512-19 15:11:56.066 4707 4707 E CrashReport: at android.os.Looper.loopOnce(Looper.java:205)
10612-19 15:11:56.066 4707 4707 E CrashReport: at android.os.Looper.loop(Looper.java:294)
10712-19 15:11:56.066 4707 4707 E CrashReport: at android.app.ActivityThread.main(ActivityThread.java:8376)
10812-19 15:11:56.066 4707 4707 E CrashReport: at java.lang.reflect.Method.invoke(Native Method)
10912-19 15:11:56.066 4707 4707 E CrashReport: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
11012-19 15:11:56.066 4707 4707 E CrashReport: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
11112-19 15:11:56.066 4707 4707 E CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
11212-19 15:11:56.071 4707 4707 D CrashReport: [Database] insert t_cr success.
11312-19 15:11:56.071 4707 4707 D CrashReport: insert t_cr success!
11412-19 15:11:56.072 4707 4707 D CrashReport: maxMemory : 256.000000
11512-19 15:11:56.072 4707 4707 D CrashReport: totalMemory : 29.115067
11612-19 15:11:56.072 4707 4707 D CrashReport: freeMemory : 226.884933


</body>
</html>

**Comment by victorfan336** [comment]
我没有给开启混淆，会是混淆的原因吗？
我去keep一下包名，只是太难复现了

**Comment by victorfan336** [comment]
我已经没有混淆日历代码了。加了:
-keep class com.necer.** {*;}


结果还是崩溃:
前后台状态:              前台

设备机型:                 23013RK75C

系统版本:                 Android 14,level 34

ROM:                       XiaoMi/MIUI

CPU架构:                 arm64-v8a

`
com.necer.calendar.NViewPager$1$onPageSelected$1.run(Unknown Source:215)
2
android.os.Handler.handleCallback(Handler.java:958)
3
android.os.Handler.dispatchMessage(Handler.java:99)
4
android.os.Looper.loopOnce(Looper.java:224)
5
android.os.Looper.loop(Looper.java:318)
6
android.app.ActivityThread.main(ActivityThread.java:8777)
7
java.lang.reflect.Method.invoke(Native Method)
8
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
9
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)`


操作步骤是调用切换日期，调用： calendar.jumpDate()的时候崩溃的

**Comment by victorfan336** [comment]
我终于复现了：
崩溃日志：

 kotlin.KotlinNullPointerException
                                                                                                    	at com.necer.calendar.NViewPager$1$onPageSelected$1.run(NViewPager.kt:79)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)


源码位置：
com.necer.calendar.NViewPager
`
init {
        addOnPageChangeListener(object : SimpleOnPageChangeListener() {
            override fun onPageSelected(position: Int) {
                super.onPageSelected(position)
                post {
                    //算出相差几页
                    var localDate = if (calendarState == CalendarState.WEEK) {
                    } else {
                       // 这里崩溃了 ！！！！
                        val intervalMonths = NDateUtil.getIntervalMonths(fulcrumDate, currentViewInitDate!!)
                    }
              }

      }
}
`

不知道是fulcrumDate = null  还是 currentViewInitDate = null 了，最好是别用 ”！！“，否则会有意想不到的惊喜。

我用的是最新版："6.0.0"

麻烦修复一下，谢谢

**Comment by liujje** [comment]
动态切换语言也会蹦 kotlin.KotlinNullPointerException
                                                                                                    	at com.necer.calendar.NViewPager$1$onPageSelected$1.run(NViewPager.kt:79)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by liujje** [comment]
直接下载源码更改，NViewPager类68行中的onPageSelected方法为 override fun onPageSelected(position: Int) {
                super.onPageSelected(position)

                // 把原来那坨逻辑封成一个函数，确保拿到 NCalendarView 再执行
                fun proceed(nCalendarView: NCalendarView) {
                    val currentViewInitDate = nCalendarView.pagerInitDate // 非空类型

                    var localDate = if (calendarState == CalendarState.WEEK) {
                        val intervalWeek = NDateUtil.getIntervalWeek(fulcrumDate, currentViewInitDate, NAttrs.firstDayOfWeek)
                        fulcrumDate.plusWeeks(intervalWeek.toLong())
                    } else {
                        val intervalMonths = NDateUtil.getIntervalMonths(fulcrumDate, currentViewInitDate)
                        fulcrumDate.plusMonths(intervalMonths.toLong())
                    }

                    localDate = getAvailableDate(localDate)

                    if (checkModel == CheckModel.SINGLE_DEFAULT_CHECKED) {
                        if (defaultCheckedFirstDate) {
                            localDate = nCalendarView.getFirstLocalDate()
                        }
                        totalCheckedDateList.clear()
                        totalCheckedDateList.add(localDate)
                    }

                    val currPageCheckedList = nCalendarView.getCurrPageCheckedDateList()
                    fulcrumDate = currPageCheckedList.firstOrNull() ?: localDate

                    notifyAllView()
                    dateChangedCallBack()
                }

                // 先尝试拿当前页；拿不到就等下一帧/布局完成再执行（只重试一次）
                post {
                    val now = findViewWithTag<NCalendarView>(currentItem)
                    if (now != null) {
                        proceed(now)
                    } else {
                        // 等到视图真正 attach、布局完成
                        viewTreeObserver.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
                            override fun onGlobalLayout() {
                                viewTreeObserver.removeOnGlobalLayoutListener(this)
                                val later = findViewWithTag<NCalendarView>(currentItem) ?: return
                                proceed(later)
                            }
                        })
                    }
                }
            }
